version: '2'

x-environment-vars: &environment-vars
  PYTHONUNBUFFERED: 1
  PYTHONIOENCODING: utf-8
  TERM: linux
  DATABASE_URL: postgres://postgres:123456@vitrina-db/postgres?sslmode=disable
  REDIS_URL: redis://vitrina-redis:6379

services:
    vitrina-service:
        build:
            context: .
            dockerfile: ./docker/Dockerfile.local
        environment:
            <<: *environment-vars
        ports:
            - "8000:8000"
        volumes:
            - .:/proj
        command: python -m code.app
        stdin_open: true
        tty: true
        depends_on:
            - "vitrina-db"
            - "vitrina-redis"
    vitrina-db:
        image: postgres:14.1-alpine
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: 123456
    vitrina-redis:
        image: redis:7.0-rc1-alpine
