FROM python:3.8-slim

RUN pip install --upgrade pip

COPY requirements/ /tmp/requirements

RUN pip install --no-cache-dir -r /tmp/requirements/dev.txt

RUN useradd -m -d /proj -s /bin/bash app
COPY . /proj
WORKDIR /proj
RUN chown -R app:app /proj/*
USER app